#include <windows.h>
#include <thumbcache.h>
#include <shobjidl_core.h>

#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <memory>
#include <new>
#include <string>
#include <vector>

namespace {
const CLSID kViewtriousStlThumbnailClsid={0xD812B4F2,0xB141,0x4A0D,{0x9A,0x4F,0x57,0x4D,0xDB,0x29,0x75,0xB2}};
std::atomic<long> g_objects=0;
struct Vec { float x,y,z; }; struct Triangle { Vec a,b,c; };
float Dot(Vec a,Vec b){return a.x*b.x+a.y*b.y+a.z*b.z;} Vec Sub(Vec a,Vec b){return {a.x-b.x,a.y-b.y,a.z-b.z};} Vec Add(Vec a,Vec b){return {a.x+b.x,a.y+b.y,a.z+b.z};} Vec Mul(Vec a,float s){return {a.x*s,a.y*s,a.z*s};} Vec Cross(Vec a,Vec b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};} Vec Normalize(Vec v){const float length=std::sqrt(Dot(v,v));return length>1e-12f?Mul(v,1.f/length):Vec{};}
bool Finite(Vec p){return std::isfinite(p.x)&&std::isfinite(p.y)&&std::isfinite(p.z);}
bool ReadAll(IStream* stream,std::vector<uint8_t>& bytes){STATSTG stat{};if(FAILED(stream->Stat(&stat,STATFLAG_NONAME))||stat.cbSize.QuadPart<84||stat.cbSize.QuadPart>64ll*1024*1024)return false;LARGE_INTEGER zero{};if(FAILED(stream->Seek(zero,STREAM_SEEK_SET,nullptr)))return false;bytes.resize(size_t(stat.cbSize.QuadPart));ULONG read=0;return SUCCEEDED(stream->Read(bytes.data(),ULONG(bytes.size()),&read))&&read==bytes.size();}
uint32_t U32(const uint8_t* p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;} float F32(const uint8_t* p){float f;std::memcpy(&f,p,4);return f;}
bool Add(std::vector<Triangle>& out,Vec a,Vec b,Vec c){if(!Finite(a)||!Finite(b)||!Finite(c))return false;const Vec n=Cross(Sub(b,a),Sub(c,a));if(Dot(n,n)>1e-20f)out.push_back({a,b,c});return out.size()<=100000;}
bool ParseBinary(const std::vector<uint8_t>& data,std::vector<Triangle>& out){if(data.size()<84)return false;const uint32_t count=U32(data.data()+80);if(count>10000000||84ull+uint64_t(count)*50!=data.size())return false;const uint32_t step=std::max(1u,(count+99999)/100000);for(uint32_t i=0;i<count;i+=step){const uint8_t* p=data.data()+84+size_t(i)*50;if(!Add(out,{F32(p+12),F32(p+16),F32(p+20)},{F32(p+24),F32(p+28),F32(p+32)},{F32(p+36),F32(p+40),F32(p+44)}))return false;}return !out.empty();}
bool ParseAscii(const std::vector<uint8_t>& data,std::vector<Triangle>& out){std::string text(reinterpret_cast<const char*>(data.data()),data.size());size_t pos=0;Vec points[3]{};int found=0;while((pos=text.find("vertex",pos))!=std::string::npos){char* end=nullptr;const char* p=text.c_str()+pos+6;Vec v{std::strtof(p,&end),0,0};if(end==p)return false;v.y=std::strtof(end,&end);v.z=std::strtof(end,&end);if(!Finite(v))return false;points[found++]=v;if(found==3){if(!Add(out,points[0],points[1],points[2]))return false;found=0;}pos=size_t(end-text.c_str());}return found==0&&!out.empty();}
bool Parse(IStream* stream,std::vector<Triangle>& triangles){std::vector<uint8_t> data;if(!ReadAll(stream,data))return false;return ParseBinary(data,triangles)||ParseAscii(data,triangles);}
uint32_t Color(uint8_t red,uint8_t green,uint8_t blue){return 0xff000000u|uint32_t(red)<<16|uint32_t(green)<<8|blue;}
HBITMAP Render(const std::vector<Triangle>& triangles,UINT requested){
    const int size=std::clamp<int>(requested,32,512);BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=size;info.bmiHeader.biHeight=-size;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;info.bmiHeader.biCompression=BI_RGB;void* pixels=nullptr;HBITMAP bitmap=CreateDIBSection(nullptr,&info,DIB_RGB_COLORS,&pixels,nullptr,0);if(!bitmap)return nullptr;
    constexpr uint32_t background=0xff1a1c20u;uint32_t* dst=static_cast<uint32_t*>(pixels);std::fill_n(dst,size_t(size)*size,background);std::vector<float> depth(size_t(size)*size,INFINITY);std::vector<Vec> normals(size_t(size)*size);
    Vec minimum=triangles.front().a,maximum=minimum;for(const auto& t:triangles)for(Vec p:{t.a,t.b,t.c}){minimum.x=std::min(minimum.x,p.x);minimum.y=std::min(minimum.y,p.y);minimum.z=std::min(minimum.z,p.z);maximum.x=std::max(maximum.x,p.x);maximum.y=std::max(maximum.y,p.y);maximum.z=std::max(maximum.z,p.z);}const Vec center{(minimum.x+maximum.x)*.5f,(minimum.y+maximum.y)*.5f,(minimum.z+maximum.z)*.5f};const float scale=std::max({maximum.x-minimum.x,maximum.y-minimum.y,maximum.z-minimum.z,1e-5f});
    // Default Z-up Model3D Home pose: yaw .62 and pitch -.42, expressed as camera axes.
    constexpr Vec homeRight{.8138785f,.5810351f,0.f};constexpr Vec homeUp{-.2369000f,.3318000f,.9130889f};constexpr Vec homeForward{-.5300000f,.7430000f,-.4077605f};
    const auto project=[&](Vec p){p=Sub(p,center);return Vec{size*.5f+Dot(p,homeRight)/scale*size*.82f,size*.5f-Dot(p,homeUp)/scale*size*.82f,Dot(p,homeForward)};};const Vec light=Normalize({-.35f,.45f,.82f});
    for(const auto& t:triangles){Vec a=project(t.a),b=project(t.b),c=project(t.c);const float area=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);if(std::fabs(area)<1e-6f)continue;Vec normal=Normalize(Cross(Sub(t.b,t.a),Sub(t.c,t.a)));const Vec faceCenter=Mul(Add(Add(t.a,t.b),t.c),1.f/3.f);if(Dot(normal,Sub(faceCenter,center))<0.f)normal=Mul(normal,-1.f);const float illumination=std::clamp(.32f+.68f*std::max(0.f,Dot(normal,light)),.22f,1.f);const uint8_t shade=uint8_t(std::lround(190.f*illumination));const int left=std::max(0,int(std::floor(std::min({a.x,b.x,c.x})))),right=std::min(size-1,int(std::ceil(std::max({a.x,b.x,c.x})))),top=std::max(0,int(std::floor(std::min({a.y,b.y,c.y})))),bottom=std::min(size-1,int(std::ceil(std::max({a.y,b.y,c.y}))));for(int y=top;y<=bottom;++y)for(int x=left;x<=right;++x){const float w0=((b.x-a.x)*(y-a.y)-(b.y-a.y)*(x-a.x))/area,w1=((c.x-b.x)*(y-b.y)-(c.y-b.y)*(x-b.x))/area,w2=1-w0-w1;if(w0<0||w1<0||w2<0)continue;const float z=w0*c.z+w1*a.z+w2*b.z;const size_t index=size_t(y)*size+x;if(z<depth[index]){depth[index]=z;normals[index]=normal;dst[index]=Color(shade,shade,shade);}}}
    constexpr uint32_t edge=0xff55595fu;for(int y=1;y<size-1;++y)for(int x=1;x<size-1;++x){const size_t index=size_t(y)*size+x,right=index+1,down=index+size_t(size);if(!std::isfinite(depth[index]))continue;const bool outline=!std::isfinite(depth[right])||!std::isfinite(depth[down]);const bool crease=std::isfinite(depth[right])&&std::isfinite(depth[down])&&(Dot(normals[index],normals[right])<.82f||Dot(normals[index],normals[down])<.82f);if(outline||crease)dst[index]=edge;}return bitmap;
}
class Provider final:public IThumbnailProvider,public IInitializeWithStream{std::atomic<ULONG> refs_{1};IStream* stream_=nullptr;public:Provider(){++g_objects;}~Provider(){if(stream_)stream_->Release();--g_objects;}HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void** value)override{if(!value)return E_POINTER;*value=nullptr;if(id==IID_IUnknown||id==IID_IThumbnailProvider)*value=static_cast<IThumbnailProvider*>(this);else if(id==IID_IInitializeWithStream)*value=static_cast<IInitializeWithStream*>(this);else return E_NOINTERFACE;AddRef();return S_OK;}ULONG STDMETHODCALLTYPE AddRef()override{return ++refs_;}ULONG STDMETHODCALLTYPE Release()override{const ULONG refs=--refs_;if(!refs)delete this;return refs;}HRESULT STDMETHODCALLTYPE Initialize(IStream* stream,DWORD)override{if(!stream||stream_)return E_INVALIDARG;stream_=stream;stream_->AddRef();return S_OK;}HRESULT STDMETHODCALLTYPE GetThumbnail(UINT size,HBITMAP* bitmap,WTS_ALPHATYPE* alpha) noexcept override{if(!bitmap||!alpha||!stream_)return E_INVALIDARG;*bitmap=nullptr;*alpha=WTSAT_UNKNOWN;try{std::vector<Triangle> triangles;if(!Parse(stream_,triangles))return E_FAIL;HBITMAP result=Render(triangles,size);if(!result)return E_OUTOFMEMORY;*bitmap=result;*alpha=WTSAT_ARGB;return S_OK;}catch(...){return E_FAIL;}}};
class Factory final:public IClassFactory{std::atomic<ULONG> refs_{1};public:HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void** value)override{if(!value)return E_POINTER;*value=nullptr;if(id==IID_IUnknown||id==IID_IClassFactory)*value=this;else return E_NOINTERFACE;AddRef();return S_OK;}ULONG STDMETHODCALLTYPE AddRef()override{return ++refs_;}ULONG STDMETHODCALLTYPE Release()override{const ULONG refs=--refs_;if(!refs)delete this;return refs;}HRESULT STDMETHODCALLTYPE CreateInstance(IUnknown* outer,REFIID id,void** value)override{if(outer)return CLASS_E_NOAGGREGATION;auto provider=new(std::nothrow) Provider;if(!provider)return E_OUTOFMEMORY;const HRESULT hr=provider->QueryInterface(id,value);provider->Release();return hr;}HRESULT STDMETHODCALLTYPE LockServer(BOOL)override{return S_OK;}};
}
extern "C" HRESULT __stdcall DllCanUnloadNow(){return g_objects==0?S_OK:S_FALSE;} extern "C" HRESULT __stdcall DllGetClassObject(REFCLSID clsid,REFIID id,void** value){if(clsid!=kViewtriousStlThumbnailClsid)return CLASS_E_CLASSNOTAVAILABLE;auto factory=new(std::nothrow) Factory;if(!factory)return E_OUTOFMEMORY;const HRESULT hr=factory->QueryInterface(id,value);factory->Release();return hr;}
